name: audiobook_organizer
description: An audiobook organizer and player with metadata management.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_slidable: ^3.0.0
  
  # State management
  provider: ^6.0.5
  
  # File handling
  path_provider: ^2.0.15
  file_picker: ^5.3.2
  path: ^1.8.3
  
  # Metadata handling
  http: ^0.13.6
  uuid: ^4.5.1
  image_picker: ^0.8.7+5
  cached_network_image: ^3.3.0 

  # Audio playback
  just_audio: ^0.10.2
  just_audio_background: ^0.0.1-beta.17
  just_audio_media_kit: ^0.0.1
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  flutter_media_metadata: ^1.0.0 
  id3: ^1.0.2
  metadata_god: ^1.0.0
  permission_handler: ^10.3.0
  
  # Utilities
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
    
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic