name: audiobook_organizer
description: An audiobook organizer and player with metadata management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  
  flutter_slidable: ^3.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  
  # File handling
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  path: ^1.8.3
  
  # Metadata handling
  uuid: ^4.5.1
  image_picker: ^0.8.7+5
  cached_network_image: ^3.3.0 

  # Audio playback
  audioplayers: ^6.1.0
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  flutter_media_metadata: ^1.0.0 
  id3: ^1.0.2
  metadata_god: ^1.0.0
  ffmpeg_kit_flutter: ^5.1.0
  permission_handler: ^10.3.0
  
  # Utilities
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0
  mime: ^1.0.4
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
    
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic